# Generated by Django 2.2 on 2021-11-09 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0002_auto_20211109_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='inclusao',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 9, 12, 33, 34, 8029), verbose_name='Inclusão'),
        ),
    ]
