# Generated by Django 2.2 on 2021-11-22 19:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0003_auto_20211122_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='inclusao',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 22, 16, 32, 32, 402561), verbose_name='Inclusão'),
        ),
    ]
