# Generated by Django 2.2 on 2021-11-23 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0010_auto_20211123_0838'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grupo',
            options={'ordering': ['nome'], 'verbose_name_plural': 'Grupos'},
        ),
        migrations.AlterField(
            model_name='grupo',
            name='inclusao',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 23, 11, 0, 43, 993756), verbose_name='Inclusão'),
        ),
    ]
