# Generated by Django 2.2 on 2021-11-24 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0015_auto_20211123_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='inclusao',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 24, 11, 12, 23, 517754), verbose_name='Inclusão'),
        ),
    ]
