# Generated by Django 2.2 on 2021-11-08 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_auto_20211108_1326'),
        ('grupos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('postos', '0001_initial'),
        ('fornecedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcordoAereo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acordo', models.CharField(max_length=50, verbose_name='Código do Acordo do Cliente')),
                ('validade', models.DateField(verbose_name='Validade do Acordo do Cliente')),
                ('desconto', models.IntegerField(verbose_name='Percentual do Desconto')),
                ('destino', models.CharField(max_length=1, verbose_name='Nacional ou Internacional')),
                ('continente', models.CharField(max_length=30, verbose_name='Nome dos Continentes')),
                ('ativo', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente')),
                ('fornecedores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fornecedores.Fornecedor')),
                ('grupos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupos.Grupo')),
                ('postos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postos.POS')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
