# Generated by Django 2.2 on 2021-11-22 18:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fornecedores', '0001_initial'),
        ('postos', '0001_initial'),
        ('grupos', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcordoAereo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oac', models.CharField(max_length=10, null=True, verbose_name='OAC')),
                ('acordo', models.CharField(max_length=50, verbose_name='Código do Acordo do Cliente')),
                ('validade', models.DateField(verbose_name='Validade do Acordo do Cliente')),
                ('desconto', models.IntegerField(verbose_name='Percentual do Desconto')),
                ('destino', models.CharField(choices=[('N', 'Nacional'), ('I', 'Internacional')], max_length=1, verbose_name='Nacional ou Internacional')),
                ('continente', models.CharField(choices=[('AM', 'América'), ('AF', 'África'), ('EU', 'Europa'), ('OC', 'Oceania'), ('AS', 'Ásia')], max_length=2, verbose_name='Nome dos Continentes')),
                ('inclusao', models.DateTimeField(default=datetime.datetime(2021, 11, 22, 15, 27, 27, 571194), verbose_name='Inclusão')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente', verbose_name='Nome do Cliente')),
                ('fornecedores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fornecedores.Fornecedor', verbose_name='Fornecedor')),
                ('grupos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupos.Grupo', verbose_name='Grupo do Cliente')),
                ('postos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postos.POS', verbose_name='POS')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'ordering': ['acordo'],
                'verbose_name': 'Acordo Aéreo',
                'verbose_name_plural': 'Acordos Aéreos',
            },
        ),
    ]
