# Generated by Django 2.2 on 2021-11-08 20:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acordos_ae', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acordoaereo',
            name='inclusao',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 17, 24, 9, 869090), verbose_name='Inclusão'),
        ),
    ]
