# Generated by Django 2.2 on 2021-11-09 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acordos_ae', '0002_acordoaereo_inclusao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acordoaereo',
            name='inclusao',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 9, 8, 14, 17, 653873), verbose_name='Inclusão'),
        ),
    ]
