# Generated by Django 2.2 on 2021-11-09 11:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acordos_ae', '0003_auto_20211109_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acordoaereo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente', verbose_name='Nome do Cliente'),
        ),
        migrations.AlterField(
            model_name='acordoaereo',
            name='fornecedores',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fornecedores.Fornecedor', verbose_name='Fornecedor'),
        ),
        migrations.AlterField(
            model_name='acordoaereo',
            name='grupos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupos.Grupo', verbose_name='Grupo do Cliente'),
        ),
        migrations.AlterField(
            model_name='acordoaereo',
            name='inclusao',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 9, 8, 31, 8, 577767), verbose_name='Inclusão'),
        ),
        migrations.AlterField(
            model_name='acordoaereo',
            name='postos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postos.POS', verbose_name='POS'),
        ),
        migrations.AlterField(
            model_name='acordoaereo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
