# Generated by Django 2.2 on 2021-11-09 13:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acordos_ae', '0005_auto_20211109_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acordoaereo',
            name='continente',
            field=models.CharField(choices=[('AM', 'América'), ('AF', 'África'), ('EU', 'Europa'), ('OC', 'Oceania'), ('AS', 'Ásia')], max_length=2, verbose_name='Nome dos Continentes'),
        ),
        migrations.AlterField(
            model_name='acordoaereo',
            name='inclusao',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 9, 10, 1, 51, 494116), verbose_name='Inclusão'),
        ),
    ]
