# Generated by Django 2.2 on 2021-11-09 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acordos_ae', '0006_auto_20211109_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acordoaereo',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='acordoaereo',
            name='inclusao',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 9, 10, 3, 50, 848969), verbose_name='Inclusão'),
        ),
    ]
