# Generated by Django 2.2 on 2021-11-09 13:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acordos_ae', '0007_auto_20211109_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acordoaereo',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='acordoaereo',
            name='inclusao',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 9, 10, 8, 16, 646870), verbose_name='Inclusão'),
        ),
    ]
