# Generated by Django 2.2 on 2021-11-11 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acordos_ae', '0010_auto_20211109_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acordoaereo',
            name='inclusao',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 11, 11, 16, 56, 779030), verbose_name='Inclusão'),
        ),
    ]
