# Generated by Django 2.2 on 2021-11-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acordos_ae', '0012_auto_20211123_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acordoaereo',
            name='inclusao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Inclusão'),
        ),
    ]
