# Generated by Django 2.2 on 2021-11-24 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acordos_ae', '0015_auto_20211123_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acordoaereo',
            name='inclusao',
        ),
    ]
