# Generated by Django 2.2 on 2021-11-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acordos_ae', '0017_acordoaereo_inclusao'),
    ]

    operations = [
        migrations.AddField(
            model_name='acordoaereo',
            name='edicao',
            field=models.DateTimeField(auto_now=True, verbose_name='Edição'),
        ),
    ]
