# Generated by Django 2.2 on 2021-11-22 18:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('postos', '0001_initial'),
        ('grupos', '0001_initial'),
        ('colaboradores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, verbose_name='Razão Social')),
                ('fantasia', models.CharField(max_length=60, verbose_name='Nome Fantasia')),
                ('vencimento', models.DateField(verbose_name='Data de Vencimento do Contrato')),
                ('vigencia', models.CharField(choices=[('12', '12'), ('24', '24'), ('36', '36'), ('48', '48'), ('IN', 'Indeterminado')], default='12', max_length=2, verbose_name='Período de Vigência do Contrato')),
                ('inclusao', models.DateTimeField(default=datetime.datetime(2021, 11, 22, 15, 27, 27, 569193), verbose_name='Inclusão')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('executivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colaboradores.Colaborador', verbose_name='Nome do Executivo')),
                ('grupos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupos.Grupo', verbose_name='Grupo de Clientes')),
                ('postos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postos.POS', verbose_name='Ponto de Atendimento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'ordering': ['nome'],
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
