# Generated by Django 2.2 on 2021-11-08 20:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grupos', '0001_initial'),
        ('postos', '0001_initial'),
        ('colaboradores', '0001_initial'),
        ('clientes', '0002_auto_20211108_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='executivo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='colaboradores.Colaborador'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='grupos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grupos.Grupo'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='inclusao',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 17, 24, 9, 867096), verbose_name='Inclusão'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='postos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='postos.POS'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
