# Generated by Django 2.2 on 2021-11-09 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_auto_20211108_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='inclusao',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 9, 8, 14, 17, 648912), verbose_name='Inclusão'),
        ),
    ]
