# Generated by Django 2.2 on 2021-11-09 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_auto_20211109_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='inclusao',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 9, 8, 31, 8, 569245), verbose_name='Inclusão'),
        ),
    ]
