# Generated by Django 2.2 on 2021-11-09 13:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_auto_20211109_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='inclusao',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 9, 10, 1, 51, 484037), verbose_name='Inclusão'),
        ),
    ]
