# Generated by Django 2.2 on 2021-11-09 15:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_auto_20211109_1008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nome'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AddField(
            model_name='cliente',
            name='vigencia',
            field=models.CharField(choices=[('12', '12'), ('24', '24'), ('36', '36'), ('48', '48'), ('IN', 'Indeterminado')], default='12', max_length=2, verbose_name='Período de Vigência do Contrato'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='executivo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='colaboradores.Colaborador', verbose_name='Nome do Colaborador'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='grupos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='grupos.Grupo', verbose_name='Grupo de Clientes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='inclusao',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 9, 12, 28, 23, 983523), verbose_name='Inclusão'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='postos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='postos.POS', verbose_name='Ponto de Atendimento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
            preserve_default=False,
        ),
    ]
