# Generated by Django 2.2 on 2021-11-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2, verbose_name='Codigo do Produto')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome do Produto')),
                ('ativo', models.BooleanField(default=False)),
            ],
        ),
    ]
