# Generated by Django 2.2 on 2021-11-24 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0017_auto_20211124_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='inclusao',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 24, 11, 50, 36, 631262), verbose_name='Inclusão'),
        ),
    ]
