# Generated by Django 2.2 on 2021-11-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0019_auto_20211124_1152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['codigo'], 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AddField(
            model_name='produto',
            name='edicao',
            field=models.DateTimeField(auto_now=True, verbose_name='Edição'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='inclusao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Inclusão'),
        ),
    ]
