# Generated by Django 2.2 on 2021-11-22 18:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aenacon', models.IntegerField(verbose_name='Valor do Fee - Aéreo Nacional Online')),
                ('aeinton', models.IntegerField(verbose_name='Valor do Fee - Aéreo Internacional Online')),
                ('honacon', models.IntegerField(verbose_name='Valor do Fee - Hotel Nacional Online')),
                ('hointon', models.IntegerField(verbose_name='Hotel Internacional Online')),
                ('canacon', models.IntegerField(verbose_name='Carro Nacional Online')),
                ('cainton', models.IntegerField(verbose_name='Carro Internacional Online')),
                ('aenacoff', models.IntegerField(verbose_name='Aéreo Nacional OffLine')),
                ('aeintoff', models.IntegerField(verbose_name='Aéreo Internacional OffLine')),
                ('honacoff', models.IntegerField(verbose_name='Hotel Nacional OffLine')),
                ('hointoff', models.IntegerField(verbose_name='Hotel Internacional OffLine')),
                ('canacoff', models.IntegerField(verbose_name='Carro Nacional OffLine')),
                ('caintoff', models.IntegerField(verbose_name='Carro Internacional OffLine')),
                ('vip', models.IntegerField(verbose_name='Vip House')),
                ('doc', models.IntegerField(verbose_name='Documentação')),
                ('fer', models.IntegerField(verbose_name='Passagem Ferroviária')),
                ('emergencial', models.IntegerField(verbose_name='Atendimento Emergencial')),
                ('ateae', models.IntegerField(verbose_name='Atendimento Aeroporto')),
                ('segViagem', models.IntegerField(verbose_name='Seguro Viagem')),
                ('passRod', models.IntegerField(verbose_name='Passagem Rodoviária')),
                ('reembolso', models.IntegerField(verbose_name='Reembolso')),
                ('cancelamento', models.IntegerField(verbose_name='Cancelamento')),
                ('assentoConf', models.IntegerField(verbose_name='Assento Conforto')),
                ('implantacao', models.IntegerField(verbose_name='Implantação')),
                ('treinamento', models.IntegerField(verbose_name='Treinamento')),
                ('consultoria', models.IntegerField(verbose_name='Gestão de Consultoria')),
                ('expense', models.IntegerField(verbose_name='Expense')),
                ('eventos', models.IntegerField(verbose_name='Eventos')),
                ('demais', models.IntegerField(verbose_name='Demais Serviços')),
                ('renovacao', models.DateField(verbose_name='Data para a Renovação do valor Fee')),
                ('inclusao', models.DateTimeField(default=datetime.datetime(2021, 11, 22, 15, 27, 27, 573194), verbose_name='Inclusão')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente', verbose_name='Nome do Cliente')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Fee',
                'verbose_name_plural': 'Fees',
            },
        ),
    ]
