# Generated by Django 2.2 on 2021-11-22 18:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='inclusao',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 22, 15, 27, 56, 352737), verbose_name='Inclusão'),
        ),
    ]
