# Generated by Django 2.2 on 2021-11-09 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_auto_20211109_0831'),
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fee',
            options={'ordering': ['cliente'], 'verbose_name': 'Fee', 'verbose_name_plural': 'Fees'},
        ),
        migrations.AddField(
            model_name='fee',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente', verbose_name='Nome do Cliente'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='aeintoff',
            field=models.IntegerField(verbose_name='Aéreo Internacional OffLine'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='aeinton',
            field=models.IntegerField(verbose_name='Valor do Fee - Aéreo Internacional Online'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='aenacoff',
            field=models.IntegerField(verbose_name='Aéreo Nacional OffLine'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='aenacon',
            field=models.IntegerField(verbose_name='Valor do Fee - Aéreo Nacional Online'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='assentoConf',
            field=models.IntegerField(verbose_name='Assento Conforto'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='ateae',
            field=models.IntegerField(verbose_name='Atendimento Aeroporto'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='caintoff',
            field=models.IntegerField(verbose_name='Carro Internacional OffLine'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='cainton',
            field=models.IntegerField(verbose_name='Carro Internacional Online'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='canacoff',
            field=models.IntegerField(verbose_name='Carro Nacional OffLine'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='canacon',
            field=models.IntegerField(verbose_name='Carro Nacional Online'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='cancelamento',
            field=models.IntegerField(verbose_name='Cancelamento'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='consultoria',
            field=models.IntegerField(verbose_name='Gestão de Consultoria'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='demais',
            field=models.IntegerField(verbose_name='Demais Serviços'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='doc',
            field=models.IntegerField(verbose_name='Documentação'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='emergencial',
            field=models.IntegerField(verbose_name='Atendimento Emergencial'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='eventos',
            field=models.IntegerField(verbose_name='Eventos'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='expense',
            field=models.IntegerField(verbose_name='Expense'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='fer',
            field=models.IntegerField(verbose_name='Passagem Ferroviária'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='hointoff',
            field=models.IntegerField(verbose_name='Hotel Internacional OffLine'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='hointon',
            field=models.IntegerField(verbose_name='Hotel Internacional Online'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='honacoff',
            field=models.IntegerField(verbose_name='Hotel Nacional OffLine'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='honacon',
            field=models.IntegerField(verbose_name='Valor do Fee - Hotel Nacional Online'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='implantacao',
            field=models.IntegerField(verbose_name='Implantação'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='passRod',
            field=models.IntegerField(verbose_name='Passagem Rodoviária'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='reembolso',
            field=models.IntegerField(verbose_name='Reembolso'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='renovacao',
            field=models.DateTimeField(verbose_name='Data para a Renovação do valor Fee'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='segViagem',
            field=models.IntegerField(verbose_name='Seguro Viagem'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='treinamento',
            field=models.IntegerField(verbose_name='Treinamento'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='vip',
            field=models.IntegerField(verbose_name='Vip House'),
        ),
    ]
