# Generated by Django 2.2 on 2021-11-11 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0004_auto_20211109_1524'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fee',
            options={'ordering': ['id'], 'verbose_name': 'Fee', 'verbose_name_plural': 'Fees'},
        ),
        migrations.AlterField(
            model_name='fee',
            name='inclusao',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 11, 11, 16, 56, 781030), verbose_name='Inclusão'),
        ),
    ]
