# Generated by Django 2.2 on 2021-11-22 22:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0008_auto_20211122_1803'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fee',
            options={'ordering': ['id'], 'verbose_name_plural': 'Fees'},
        ),
        migrations.AlterField(
            model_name='fee',
            name='inclusao',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 22, 19, 12, 26, 434407), verbose_name='Inclusão'),
        ),
    ]
