# Generated by Django 2.2 on 2021-11-23 19:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0013_auto_20211123_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='inclusao',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 23, 16, 21, 31, 942506), verbose_name='Inclusão'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='renovacao',
            field=models.DateField(verbose_name='Data para a Renovação do Fee'),
        ),
    ]
