# Generated by Django 2.2 on 2021-11-05 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, verbose_name='Codigo do Ponto de Atendimento')),
                ('nome', models.CharField(max_length=60, verbose_name='Nome do Ponto de Atendimento')),
                ('ativo', models.BooleanField(default=False)),
            ],
        ),
    ]
