# Generated by Django 2.2 on 2021-11-05 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Razão Social', max_length=60)),
                ('fantasia', models.CharField(help_text='Nome Fantasia', max_length=60)),
                ('rede', models.CharField(help_text='Grupo do Fornecedor', max_length=60)),
                ('ativo', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Fornecedores',
                'verbose_name': 'Fornecedor',
                'ordering': ['nome'],
            },
        ),
    ]
