# Generated by Django 2.2 on 2021-11-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='fantasia',
            field=models.CharField(max_length=60, verbose_name='Nome Fantasia'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='nome',
            field=models.CharField(max_length=60, verbose_name='Razão Social'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='rede',
            field=models.CharField(max_length=60, verbose_name='Grupo do Fornecedor'),
        ),
    ]
