# Generated by Django 2.2 on 2021-11-09 15:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('produtos', '0002_auto_20211109_1232'),
        ('fornecedores', '0002_auto_20211109_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='inclusao',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 9, 12, 32, 22, 405602), verbose_name='Inclusão'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='produtos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='produtos.Produto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
