# Generated by Django 2.2 on 2021-11-09 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0003_auto_20211109_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='inclusao',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 9, 12, 33, 34, 23649), verbose_name='Inclusão'),
        ),
    ]
