# Generated by Django 2.2 on 2021-11-22 18:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fornecedores', '0001_initial'),
        ('postos', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarifario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoQuarto', models.CharField(max_length=3, verbose_name='Tipo de Apartamento')),
                ('diaria', models.IntegerField(verbose_name='Valor da Diária')),
                ('taxa', models.IntegerField(verbose_name='Valor das Taxas')),
                ('tarifaQualif', models.BooleanField(default=False, verbose_name='Se a Tarifa é Qualificada com o Fornecedor')),
                ('tarifaAcordo', models.BooleanField(default=False, verbose_name='Tarifa Acordo')),
                ('tarifaFlut', models.BooleanField(default=False, verbose_name='Tarifa Flutuante')),
                ('validade', models.DateField(verbose_name='Vencimento da Tarifa')),
                ('inclusao', models.DateTimeField(default=datetime.datetime(2021, 11, 22, 15, 27, 27, 575195), verbose_name='Inclusão')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente', verbose_name='Cliente')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fornecedores.Fornecedor', verbose_name='Fornecedor')),
                ('pos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postos.POS', verbose_name='POS')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'ordering': ['cliente'],
                'verbose_name': 'Tarifário',
                'verbose_name_plural': 'Tarifários',
            },
        ),
    ]
