# Generated by Django 2.2 on 2021-11-23 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarifarios', '0009_auto_20211122_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifario',
            name='inclusao',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 23, 8, 38, 0, 982867), verbose_name='Inclusão'),
        ),
    ]
