# Generated by Django 2.2 on 2021-11-08 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_auto_20211108_1724'),
        ('colaboradores', '0001_initial'),
    ]

